version: '3'


services:
  elecciones-micro:
    build: ./parcial-2-elecciones-2023-
    image: elecciones-app
    ports:
      - "8084:8084"
    environment:
      APP_NAME: elecciones-app


  eleccionesApiExterna:
    image: tupfrcutn/elecciones-2023:1.0.0
    ports:
      - "8080:8080"

  api-gateway:
    image: sha256:6bc4940bec31d311b67ee8d5fadfe3d79f8bfae25e4c5306a426d8632ce258e1
    ports:
      - "8081:8081"
